### PR TITLE
Externalize ES index name

### PR DESCRIPTION
**Pull request by tlrx**
ES name used in demo is externalize in a var => it will simplify index switching

### CODE REVIEW

**Comment by dadoonet** [comment]
Thanks Tanguy. Could you please pull my repo (branch gh-pages) and merge it on your side? I can not automatically merge your changes.
(I've made some changes yesterday and it's now published automatically on the web)

**Comment by dadoonet** [comment]
OMG!

**Comment by tlrx** [comment]
:)

**Comment by arcolife** [comment]
Hahahaha .. Slick! such schedulers. Much wonders

**Pull request closed without merging**
